# Generated by Django 5.0.1 on 2024-01-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinToss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chosen_side', models.CharField(choices=[('HEAD', 'Head'), ('TAIL', 'Tail')], max_length=4)),
                ('result', models.CharField(blank=True, choices=[('HEAD', 'Head'), ('TAIL', 'Tail')], max_length=4, null=True)),
                ('win', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
