# Generated by Django 5.0.1 on 2024-01-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
