# Generated by Django 5.0.1 on 2024-01-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_cointoss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinToss',
        ),
    ]
