# Generated by Django 5.0.1 on 2024-04-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_joined',
            new_name='date_joined',
        ),
    ]
