# Generated by Django 4.2.11 on 2024-04-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_userprofile_avatar_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
    ]
