# Generated by Django 4.2.11 on 2024-04-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_remove_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
