# Generated by Django 4.2.11 on 2024-04-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
