# Generated by Django 4.2.11 on 2024-04-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
