# Generated by Django 5.0.1 on 2024-01-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_alter_prediction_user_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
