# Generated by Django 4.2.11 on 2024-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
