# Generated by Django 5.0.1 on 2024-01-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
